dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: lLHV1FRxQy4OeoReS5wxaULSYiotOQ5Diu3Lf+KmhH3g0oEOatcpI/EwKwSLZV6NBCCfUQy3DRR2UPkyfL+Ot2ln8zGpovh/rHxF4y7OTuVjJ81I7JCNTeKRH7fVXmYYOoHDq++I6O1yQprvoTb3vYhVbxo4Vwm26hqHg94GF2vDxQr0Ufka+seLE4DgS5ouxVJ348pNDSbFTaYbXw5l6MZiqkWpkInnN7TdaAeMyU3BBMIUhkSXYPRgmqFpy+kDuYdJ7St65eLHbGwHDMEn03yNISK9pWCkUALU8ElQfvh2BGwjdLppYe5UgZPYvfgvN8d3CdxFSY/DqkQlHvS65SSeEnTiTuXuuSlVbsrrV9bpjYzPOyNgtTFbb20vssNIMUfTML8JVau6DTZyLcqgAnwM3Urwx3byJybnMJqaBqc5ho45Oh48zPcxJe27OSgackFTFG1gRSAcRboq+akOVAfRzxa2CyudcKKMTOXP05zN50VT83pFN/A/vm4ycMeJLtqJAv/fzNNCDxU0E1u8fw4WG1K75IgtYB/oGr4fO4oh/5aun6IZfnLB4ZnqBlnL8bTP4Y9V6AcrnYuyex6wuzc+3BLXF6htG97awhgJk1KoIh/RqKWnG/+GycGBP337WqTg7V8Ic/YsXXwLGhSUVMIaR7wKmZhqScvhB1eLvsA=
